### ISSUE TITLE
Workbench does not appear in the drop down list

### ISSUE THREAD

**Issue by xraf32** [chbergmann/CurvedShapesWorkbench#11]
Hi there, I have installed the workbench via the addon manager, restarted FreeCad and it still won't show up in the drop down list. I have installed another workbench after that and that one shows up. There is a folder "CurvedShapes" full of python scripts in the folder ~/.FreeCad/Mod

System data:
OS: Debian GNU/Linux 10 (buster)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.
Build type: Release
Python version: 2.7.16rc1
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

**Comment by SMerrony** [comment]
Same here.  I see the following error in the Report View...

During initialization the error Non-ASCII character '\xc2' in file /home/steve/.FreeCAD/Mod/CurvedShapes/CurvedShapes.py on line 242, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (CurvedShapes.py, line 242) occurred in /home/steve/.FreeCAD/Mod/CurvedShapes/InitGui.py

**Comment by inpatientia** [comment]
Thank you NearlyEnjoyable!  You clued me in to the reason why various libraries simply weren't available.  Freecad's CurvedShapes library wasn't loading correctly, FcGear and Curves workbenches didn't show at all.  Update Alternatives gave me two freecad-python3 options, the second in the list enabled both!

**Comment by luzpaz** [comment]
This ticket should be closed.
