### ISSUE TITLE
unexplained twisting happening when trying to use "Curved Segment: Interpolates a 3d shape between two 2D curves and optional hullcurves"

### ISSUE THREAD

**Issue by yashasweeyash** [chbergmann/CurvedShapesWorkbench#13]
Description:
unexplained twisting happening when trying to use "Curved Segment: Interpolates a 3d shape between two 2D curves and optional hullcurves"

Reproduction steps:
1) create a circle on one end 
2) a mirrored bspline on other end. 
3) use the feature "Curved Segment: Interpolates a 3d shape between two 2d Curves and option hullcurves"

The issue happens even without the shown guide curve in the images below, so those guide curves can be ignored while trying to reproduce the issue.
![Screenshot from 2021-01-16 02-53-52](https://user-images.githubusercontent.com/7886764/104767104-9d4a1e00-57a6-11eb-8c1c-163abd8d7de0.png)
![Screenshot from 2021-01-16 02-53-35](https://user-images.githubusercontent.com/7886764/104767112-a0450e80-57a6-11eb-8e4b-37f03504b23a.png)
![Screenshot from 2021-01-16 02-52-45](https://user-images.githubusercontent.com/7886764/104767117-a33fff00-57a6-11eb-9de6-d01e38f765d4.png)

**Comment by yashasweeyash** [comment]
Update: This happens even when the bspline is not mirrored.

**Comment by luzpaz** [comment]
@chbergmann care to weigh-in ?
