### ISSUE TITLE
LasercutterTechdrawExport error

### ISSUE THREAD

**Issue by franc-pedro** [chbergmann/CurvedShapesWorkbench#15]
Hello
Thirst of all thank you for this great workbench.
There is an error in LasercutterTechdrawExport.py on line 63.

**Comment by afitphud** [comment]
Here's the specific error message from Report View...

11:00:48  invalid syntax (LasercutterTechdrawExport.py, line 63)
11:00:48  Traceback (most recent call last):
  File "<string>", line 28, in Initialize
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

**Comment by franc-pedro** [comment]
In fact is just an extra colon in LasercutterTechdrawExport.py on line 63. In linux you can edit ~/.FreeCAD/Mod/CurvedShapes/LasercutterTechdrawExport/LasercutterTechdrawExport.py and delete the extra colon.

**Comment by afitphud** [comment]
For windows they get installed in the C:\Users\<username>\Appdata\Roaming\FreeCAD\Mod directory.

Corrected the hanging colon on line 63 and it works like a champ - thanks!

**Comment by chbergmann** [comment]
Sorry for this stupid bug. It has been fixed.
