### ISSUE TITLE
CurvedArray - twist working incorrectly

### ISSUE THREAD

**Issue by Shkolik** [chbergmann/CurvedShapesWorkbench#28]
Tried to create wing with Curved array tool. By my design wing should have twist, but property "Twist" on stated tool just rotates whole array instead twisting it. 

Without twist:
![image](https://github.com/chbergmann/CurvedShapesWorkbench/assets/26121979/0c38e2d8-c2da-4d6f-9b34-696a35bcec6e)

With twist applied:
![image](https://github.com/chbergmann/CurvedShapesWorkbench/assets/26121979/9e6b446c-3f22-480f-8464-4eb7c3230c8c)

PS: Curved Path Array works fine, but it less suitable for my task.

Sample file:
[curvedshapes_twist.zip](https://github.com/chbergmann/CurvedShapesWorkbench/files/14592303/curvedshapes_twist.zip)

**Comment by chbergmann** [comment]
I fixed it.

**Comment by Shkolik** [comment]
Still same error:
![image](https://github.com/chbergmann/CurvedShapesWorkbench/assets/26121979/44497b4d-83e1-40f1-ae80-6dae47fbfef7)

`OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * CurvedShapes 1.0.7
  * Curves 0.6.28
  * fasteners 0.5.13
  * Foamcut 0.1.1
  * Marz 0.0.29-alpha
  * PieMenu 1.3.9
`

**Comment by chbergmann** [comment]
sorry, there was still something wrong. Please update the workbench again.

**Comment by Shkolik** [comment]
Now it's working! Thanks for your effort.
