### ISSUE TITLE
Feature Request: Configure degree of Loft for surface/solid objects

### ISSUE THREAD

**Issue by AIRCAP** [chbergmann/CurvedShapesWorkbench#36]
Internally CurvedShapes uses a "Loft" over the wires of the ribs generated by Curved Arrays or Segment.
Right now the "degree" of this loft is hardcoded to "5" -- this works typically well for "linear" rib distribution, but for other rib distributions and depending on the hullcurve and twists in the base shapes - especially for CurvedSegments , the loft generation can cause unwanted oscillations, distortions and/or fail completely (crash or freeze freecad)

The workaround right now is to
1. only create wires (no turn surface and solid to false)
2. use the Part:ExplodeCompound filter to extract the individual rib shapes.
3. manually loft all these ribs and specify a custom degree for the loft.

This workaround is, however, cumbersome, since the ExplodeCompound function, although it creates clones of the ribs, does not update if the number of ribs changes. 

It would be easier if the degree of the loft was a configurable parameter in the CurvedArray, PathArray or Segment and/or if the existing InterpolationPoints setting were to be used.   for backwards compatibility it would probably be best to introduce a new parameter which defaults to 5 (the current hardcoded value)

**Comment by chbergmann** [comment]
Thank you for the contribution
