### ISSUE TITLE
What is the official SVG icon of this WB?

### ISSUE THREAD

**Issue by luzpaz** [chbergmann/CurvedShapesWorkbench#4]
Is it https://github.com/chbergmann/CurvedShapesWorkbench/blob/master/Resources/icons/curvedArray.svg ?

Reason: The FreeCAD Addon Manager was just updated and we're bundling all addon workbench logos in to FreeCAD core (JIC the user doesn't have internet access or there is an issue with connectivity etc.. the icon of the workbench will still be visible).  

Related: https://forum.freecadweb.org/viewtopic.php?f=9&t=36556&start=30#p314729

**Comment by chbergmann** [comment]
yes, it is https://github.com/chbergmann/CurvedShapesWorkbench/blob/master/Resources/icons/curvedArray.svg

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/pull/2328
